const fs = require('fs');
const path = require('path');

// Define the S3 base URL
const s3BaseUrl = "https://eecs4413-3dmodels.s3.ca-central-1.amazonaws.com";

// Your existing model data (copy-paste this block)
const models = [
  { name: "Messerschmitt Bf-109 - Chicken Gun Plane", path: "${s3BaseUrl}/models/planes/planes-model1.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model1-thumbnail.png", price: '25.99', author: { displayName: 'amogusstrikesback2' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Chernovan Nemesis Plane", path: "${s3BaseUrl}/models/planes/planes-model2.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model2-thumbnail.png", price: '29.99', author: { displayName: 'Swiss_Fox'}, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "Cessna 172 Plane", path: "${s3BaseUrl}/models/planes/planes-model3.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model3-thumbnail.png", price: '24.99', author: { displayName: 'osmosikum' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."  },
  { name: "1932 Gee Bee Model R-2 Plane", path: "${s3BaseUrl}/models/planes/planes-model4.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model4-thumbnail.png", price: '23.99', author: { displayName: 'Ruu' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "1914 Stahltaube Pigeon Hole Plane", path: "${s3BaseUrl}/models/planes/planes-model5.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model5-thumbnail.png", price: '21.99', author: { displayName: 'Tijmen Matthys'}, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "Airco DH9A WW1 Plane", path: "${s3BaseUrl}/models/planes/planes-model6.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model6-thumbnail.png", price: '29.99', author: { displayName: 'Cleuza Costa' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "Sopwith Dolphin Plane", path: "${s3BaseUrl}/models/planes/planes-model7.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model7-thumbnail.png", price: '25.99', author: { displayName: 'Mathias Tossens' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "Polygonal Toy Plane", path: "${s3BaseUrl}/models/planes/planes-model8.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model8-thumbnail.png", price: '24.99', author: { displayName: 'arifaydn99' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },
  { name: "Aves Transporter Engine", path: "${s3BaseUrl}/models/planes/planes-model9.glb", thumbnail: "${s3BaseUrl}/models/planes/planes-model9-thumbnail.png", price: '24.99', author: { displayName: 'VertaScan' }, category: "planes", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },

  { name: "Medieval Fantasy Book", path: "${s3BaseUrl}/models/environments/environment-model1.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model1-thumbnail.png", price: '39.99', author: { displayName: 'Pixel' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Baba Yaga's Hut", path: "${s3BaseUrl}/models/environments/environment-model2.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model2-thumbnail.png", price: '39.99', author: { displayName: 'Inuciian' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Winter Medieval Fantasy Tavern", path: "${s3BaseUrl}/models/environments/environment-model3.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model3-thumbnail.png", price: '38.99', author: { displayName: 'Rixael' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Amusement Park Island", path: "${s3BaseUrl}/models/environments/environment-model4.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model4-thumbnail.png", price: '35.99', author: { displayName: 'Omid Saadat' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Medieval Fantasy Tavern", path: "${s3BaseUrl}/models/environments/environment-model5.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model5-thumbnail.png", price: '34.99', author: { displayName: 'Rixael' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Fantasy Town", path: "${s3BaseUrl}/models/environments/environment-model6.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model6-thumbnail.png", price: '31.99', author: { displayName: 'arturhorn' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Village Project: Watermill", path: "${s3BaseUrl}/models/environments/environment-model7.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model7-thumbnail.png", price: '38.99', author: { displayName: 'Callum Steel' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Lighthouse at Portal Crossroads", path: "${s3BaseUrl}/models/environments/environment-model8.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model8-thumbnail.png", price: '36.99', author: { displayName: 'Nortenko Dmytro' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Taksim Tunel", path: "${s3BaseUrl}/models/environments/environment-model9.glb", thumbnail: "${s3BaseUrl}/models/environments/environment-model9-thumbnail.png", price: '35.99', author: { displayName: 'Gürkan GÜRBÜZ' }, category: "environments", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},

  { name: "Lamborghini Centenario LP-770 Baby Blue SDC", path: "${s3BaseUrl}/models/cars/cars-model1.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model1-thumbnail.png", price: '29.99', author: { displayName: 'SDC PERFORMANCE' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Porsche 917 Living Legend 2013", path: "${s3BaseUrl}/models/cars/cars-model2.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model2-thumbnail.png", price: '35.99', author: { displayName: 'kevin (ケビン)' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Lotus Exige 240", path: "${s3BaseUrl}/models/cars/cars-model3.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model3-thumbnail.png", price: '34.99', author: { displayName: 'D3DARTM' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Lamborghini Aventador SVJ - SC20 EDITION", path: "${s3BaseUrl}/models/cars/cars-model4.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model4-thumbnail.png", price: '36.99', author: { displayName: 'SDC PERFORMANCE' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "McLaren Spider", path: "${s3BaseUrl}/models/cars/cars-model5.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model5-thumbnail.png", price: '34.99', author: { displayName: 'SINNIK' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "F1 2021 McLaren MCL35M", path: "${s3BaseUrl}/models/cars/cars-model6.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model6-thumbnail.png", price: '32.99', author: { displayName: 'Excalibur' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Hennessey Venom F5 2021", path: "${s3BaseUrl}/models/cars/cars-model7.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model7-thumbnail.png", price: '36.99', author: { displayName: 'kevin (ケビン)' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Porsche Mission E", path: "${s3BaseUrl}/models/cars/cars-model8.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model8-thumbnail.png", price: '39.99', author: { displayName: 'kevin (ケビン)' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Vision 1789 | 2021", path: "${s3BaseUrl}/models/cars/cars-model9.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model9-thumbnail.png", price: '35.99', author: { displayName: 'kevin (ケビン)' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Peugeot 9x8 Hypercar", path: "${s3BaseUrl}/models/cars/cars-model10.glb", thumbnail: "${s3BaseUrl}/models/cars/cars-model10-thumbnail.png", price: '39.99', author: { displayName: 'kilianhoffmann13' }, category: "cars", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency." },

  { name: "Orange Bird", path: "${s3BaseUrl}/models/animals/animals-model1.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model1-thumbnail.png", price: '19.99', author: { displayName: 'Wen Yeh' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Raccoon", path: "${s3BaseUrl}/models/animals/animals-model2.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model2-thumbnail.png", price: '14.99', author: { displayName: 'Santrez' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Duck Quick Quack", path: "${s3BaseUrl}/models/animals/animals-model3.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model3-thumbnail.png", price: '18.99', author: { displayName: 'pepetrincado' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Dancing Penguin", path: "${s3BaseUrl}/models/animals/animals-model4.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model4-thumbnail.png", price: '17.99', author: { displayName: 'twilighthall83' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Zebra", path: "${s3BaseUrl}/models/animals/animals-model5.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model5-thumbnail.png", price: '19.99', author: { displayName: 'kenchoo' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Labrador Dog", path: "${s3BaseUrl}/models/animals/animals-model6.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model6-thumbnail.png", price: '18.99', author: { displayName: 'kenchoo' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Bicolor Cat", path: "${s3BaseUrl}/models/animals/animals-model7.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model7-thumbnail.png", price: '16.99', author: { displayName: 'kenchoo' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: " Grey Rhino", path: "${s3BaseUrl}/models/animals/animals-model8.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model8-thumbnail.png", price: '21.99', author: { displayName: 'LasquetiSpice' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Giraffe", path: "${s3BaseUrl}/models/animals/animals-model9.glb", thumbnail: "${s3BaseUrl}/models/animals/animals-model9-thumbnail.png", price: '19.99', author: { displayName: 'Amx360' }, category: "animals", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},

  { name: "Son Goku - Dragon Ball Z", path: "${s3BaseUrl}/models/characters/character-model1.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model1-thumbnail.png", price: '29.99', author: { displayName: 'Kari' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Monkey D. Luffy - Once Piece", path: "${s3BaseUrl}/models/characters/character-model2.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model2-thumbnail.png", price: '35.99', author: { displayName: 'nitwit.friends' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Naruto Uzumaki - Naruto Shippuden", path: "${s3BaseUrl}/models/characters/character-model3.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model3-thumbnail.png", price: '25.99', author: { displayName: 'ronildo.facanha' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Kakashi Hatake - Naruto Shippuden", path: "${s3BaseUrl}/models/characters/character-model4.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model4-thumbnail.png", price: '39.99', author: { displayName: 'minhdoan' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Prince Vegeta", path: "${s3BaseUrl}/models/characters/character-model5.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model5-thumbnail.png", price: '34.99', author: { displayName: 'schischu' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Saitama - One Punch Man", path: "${s3BaseUrl}/models/characters/character-model6.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model6-thumbnail.png", price: '36.99', author: { displayName: 'MMKH' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Ash Ketchum - Pokemon", path: "${s3BaseUrl}/models/characters/character-model7.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model7-thumbnail.png", price: '34.99', author: { displayName: 'Pablo Iglesias Diéguez' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Tanjiro Kamado - Demon Slayer", path: "${s3BaseUrl}/models/characters/character-model8.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model8-thumbnail.png", price: '49.99', author: { displayName: 'K-' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
  { name: "Ichigo Kurosaki - Bleach", path: "${s3BaseUrl}/models/characters/character-model9.glb", thumbnail: "${s3BaseUrl}/models/characters/character-model9-thumbnail.png", price: '24.99', author: { displayName: 'mikomagallona' }, category: "characters", description: "This is a beautifully crafted 3D model. Suitable for a variety of use cases such as games, simulations, or creative projects. The model is detailed and optimized for performance, ensuring a balance between visual fidelity and runtime efficiency."},
];



// Function to replace string placeholders with template literals
function replaceWithTemplateLiteral(modelArray) {
  return modelArray.map(model => ({
    ...model,
    path: `${s3BaseUrl}${model.path.replace("${s3BaseUrl}", "")}`,
    thumbnail: `${s3BaseUrl}${model.thumbnail.replace("${s3BaseUrl}", "")}`
  }));
}

// Replace the placeholders
models = replaceWithTemplateLiteral(models);

// Save the updated models array back to a file or console log it
const outputFile = path.join(__dirname, 'updatedModels.json');
fs.writeFileSync(outputFile, JSON.stringify(models, null, 2));

console.log("Models updated successfully.");
